apiVersion: v1
kind: Pod
metadata:
  name: app-volumeMounts
spec:
  containers:
  - name: app-container
    image: gcr.io/kuar-demo/kuard-amd64:1
    ports:
    - containerPort: 8080
    livenessProbe:
      httpGet:
        path: /health
        port: 8080
    readinessProbe:
      httpGet:
        path: /readiness
        port: 8080
    volumeMounts:
    - name: host-path-volume
      mountPath: /data
  volumes:
  - name: host-path-volume
    hostPath:
      path: /host-path
