apiVersion: v1
kind: Pod
metadata:
  name: app-livenessProbe
spec:
  containers:
  - name: app-container
    image: gcr.io/devops-course-405218/demo:v2.0.0
    ports:
    - containerPort: 8000
    livenessProbe:
      httpGet:
        path: /
        port: 8000
